<?php

//
//default configuration page
//


//igk_die("kd");
//confirguration view 
// igk_wln("frame :  ".$this->ConfigFrame);

igk_html_rm($this->ConfigFrame);
$t->ClearChilds();
($cl = $t["class"]) && $cl->clear();
$t["class"]="igk-cnf-page";


// igk_wln("te :  ".$this->ConfigMenuNode->ParentNode);


$h = $t->addIGKSysHeaderBar();
$h->Title = "Balafon";
$gdoc = igk_app()->Doc;
igk_google_addfont($gdoc, "Open Sans", 400, 1);
$f = $this->getStylesDir()."/config.pcss";

$gdoc->Theme->addTemporaryFile($f);


// $t->addtoggleStateButton("clj");
// $t->addDiv()->Content = "OK";

// return;

//toggle button only visible for small device
$navbtn = $h->Box->addToggleButton();
$navbtn->Target = "#android-menu";
$navbtn->setClass("igk-sm-only igk-xsm-only floatr");
$navbtn->ClassProperty = "posab igk-col-sm-3-2";
$navbtn->addBar(3);

$android_menu = $h->Box->addDiv();//("ul");
$android_menu->setId("android-menu");
$android_menu["class"] = "igk-mob-opts igk-sm-only";
$android_menu["igk-data-menu"] = 1;
$android_menu["igk-data-menu-binding"] = "#igk-cnf-menu";


$t->addDiv()->add($this->ConfigFrame);

$t->addDiv()->setClass("igk-cnf-footer")->addContainer()
->addRow()->addCol()->addDiv()->setClass("alignc")->Content = IGK_COPYRIGHT;
?>