<?php
$t->clearChilds();
$t->addDiv()->addTitleLevel(4)->Content = R::ngets("title.SubdomainManager");
$t->addHSep();

$dom = IGKSubDomainManager::GetBaseDomain();
$dv = $t->addDiv();
$dv["class"]  = "igk-roll-owner";
$dv->Content = $dom;

$dv->addRollIn()->setClass("igk-pull-right")->addAJXA($this->getUri("dom_add_db_edit_domain_ajx"))->addResImg("edit_16x16");

$tdv = $t->addDiv();
$tdv["class"] = "bgcl-white igk-row";
$tdv["style"] = "margin:0px; margin-bottom:10px;";

$tdv->addDiv()->addTitleLevel(5)->Content = R::ngets("title.SystemDomain");
$vlist = IGKSubDomainManager::getInstance()->domainList();


$dv = $tdv->addDiv();
foreach($vlist as $k=>$v){
	$dv->add("div")->setClass("floatl")->setStyle("width:180px;")->Content = $v;
}


$tdv = $t->addDiv();
$tdv["class"] = "c-z bgcl-white igk-write";

$tdv->addDiv()->addTitleLevel(5)->Content = R::ngets("title.DatbaseRegisteredDomain");

igk_notifyctrl()->setNotifyHost($tdv->addDiv(), "domain/dbz");
// igk_wln($this->DataTableName);
$db = igk_db_table_select_where($this->DataTableName,null, $this);
if (!$db)
{
	$tdv->addNotifyBox("danger")->Content = R::ngets("err.cantgetdomainlist");
}
else{
	$c = $db->RowCount;	
	if ($c>0){
	$tdv->addDiv()->Content = $c>1 ? "Entries : ".$c : $c;
	
	$tb = $tdv->addForm()->addTable();
	$tb["class"] = "igk-central";
	$tb["style"] = "margin:auto; min-width: 500px;";
	$tr = $tb->add("tr");	
	IGKHtmlUtils::AddToggleAllCheckboxTh($tr);//->add("th"));//->addSpace();
	$tr->add("th")->setClass("igk-col-4-2")->Content = R::ngets("lb.clName");
	$tr->add("th")->setClass("fitw")->Content = R::ngets("lb.clCtlr");
	$tr->add("th")->addSpace();
		$scheme = igk_sys_srv_uri_scheme()."://";
		foreach($db->Rows as $k=>$v){
			$tr = $tb->add("tr");
			$tr->add("td")->addInput("item[]", "checkbox", $v->clId);
			$uri = $scheme.$v->clName.".".$dom;
			$tr->add("td")->addA($uri)->Content = $v->clName.".".$dom;
			$tr->add("td")->Content = $v->clCtrl;
			
			$tr->add("td")->addAJXA($this->getUri("dom_edit_domain_ajx&i=".$v->clId))->addResImg("edit_16x16");
			$tr->add("td")->addAJXA($this->getUri("dom_drop_domain_ajx&i=".$v->clId))->addResImg("drop_16x16");
		}
	}
}

$b = $tdv->addForm()
->addActionBar()->setClass("no-margin");
$b->addAJXA($this->getUri("dom_add_db_domain_ajx"))->addResImg("add_16x16");
$a = $b->addA($this->getUri("dom_drop_db_s_domain_ajx"));
$a["onclick"] = "javascript: var s = \$igk(this).select(\"^.c-z\").getItemAt(0).select(\"form\").getItemAt(0);".
"ns_igk.ajx.postform(s.o, this.href, ns_igk.ajx.fn.replace_or_append_to_body); return false;";
$a->addResImg("drop_16x16");
?>