<?php
$app = igk_app();


$fclist = array("install"=>function(){

$app = igk_app();
	$o = igk_get_robj();
	$e = 0;
	
	if (empty($o->cladminDomain)){
		$e = 1;
		igk_notifyctrl("wizeinstall")->addErrorr("e.domainrequire");
	}	
	if (empty($o->cladminWebPageTitle)){
		$e = 1;
		igk_notifyctrl("wizeinstall")->addErrorr("e.setwebpagetitle");
	}
	
	//check password
	if ($o->cladminPassword == $o->cladminrePassword){
		if (empty($o->cladminPassword))
			$o->cladminPassword = "admin";		
	}
	else{
		igk_notifyctrl("wizeinstall")->addErrorr("e.passwordrequired");
		$e = 1;
	}	
	if (!$e && ($o->clDbUserPassword !== $o->clDbUserRePassword)){		
		$e = 1;
	}	
	igk_notification_push_event("sys://event/check_wizeinstall", $o);	
	$es = "::Error";
	
	
	if (!isset($o->$es) && !$e){
		
		//db 
		$app->Configs->admin_pwd = md5($o->cladminPassword);
		$app->Configs->website_domain = $o->cladminDomain;
		$app->Configs->website_title = $o->cladminWebPageTitle;
		
		//db setting
		$app->Configs->db_name = $o->clDbName;
		$app->Configs->db_server = $o->clDbServer;
		$app->Configs->db_user = $o->clDbUserLogin;
		$app->Configs->db_pwd = $o->clDbUserPassword;
		
		igk_save_config();	
		
		
		//reset session wize install 
		$app->Session->setParam("igk_wizeinstall", null);
		// $d = igk_createNode("div");
		// $d->addScript()->Content = "window.location = '".igk_io_baseUri("/Configs")."';";
		// $d->RenderAJX();	
		//destroy session to force realod page
		session_destroy();		
		igk_navto(igk_io_baseUri("/Configs"));
		igk_exit();
	}else{
		//igk_notifyctrl("wizeinstall")->addErrorr("e.wizecontains.error");
	}
});
$is_install = (igk_getv($params,0) == "install");
if ($is_install)
igk_handle_view_cmd($params, $fclist);


	
igk_app()->Session->setParam("igk_wizeinstall", 1);

$doc->head->addCssLink("https://fonts.googleapis.com/css?family=Roboto:300");
$doc = igk_get_document(__FILE__);
$doc->Title = "Balafon - Setup - [IGKDEV]";
$doc->Favicon = new IGKHtmlRelativeUriValueAttribute("Lib/igk/Default/R/Img/balafon.ico");
$doc->Theme->addTemporaryFile(dirname(__FILE__)."/../Styles/wizeinstall.pcss");

$bbox = $doc->body->addBodyBox();
$bbox->ClearChilds();



$t = $bbox->addDiv();
$t["class"]="+igk-wi";//wize install


$t->addDiv()->setClass("posfix fitw fith")->addSvgSymbol("balafon_logo");
$conf_ctrl = igk_getctrl(IGK_CONF_CTRL);

$box = $t->addDiv()->addDialogBox(R::ngets("title.wizeinstall"));
$box["igk:data"] = "{closeBySubmit:1, noClose:1}";
$box["class"]="no-close";
$c = $box->addDialogBoxContent()->setStyle("background-color:#fdfdfd");



$f = igk_io_dir(IGK_LIB_DIR."/license.txt");



$dv = $c->addRow()->addDiv();
$dv->addNotifyHost("wizeinstall");
//setup form
$frm = $dv->addForm();
$frm["action"]=igk_io_baseUri()."/Configs/?wizeinstall=1";
$frm["method"]="POST";
$frm->addInput("install", "hidden",1);
$frm->addInput("igk-winstall", "hidden",1);


$dv = $frm->addDiv();


//create a page view create by global target node but hosted to div
$hpage = $dv->add($t->addNodeCallback("pageview", function($t){	
	return $t->addHorizontalPageView()->setId("pageview");
}));
$hpage->clearChilds();


if (!$is_install){
//start page
$d = $hpage->addDiv()->setId("welcome");
$d->addRow()->setStyle("margin:3em")->setClass("no-overflow")->addArticle($conf_ctrl, "wizeinstall.welcome");


//licence page
$d = $hpage->addDiv()->setId("license");
$d->addQuote()->addSectionTitle(4)->Content = R::ngets("title.Licence");
$d->addReadOnlyTextZone($f)->setStyle("height: 320px; font-size:0.88em;padding:10px; ");
}

//admin page
$d = $hpage->addDiv()->setId("admin");
$d->addDiv()->addSectionTitle(4)->Content = R::ngets("title.adminsetting");
$g = $d->addDiv();
$gr = $g->addRow();
$gr->addCol("igk-col-3-1")->addDiv()->addSvgSymbol("admin_logo");
igk_html_buildform($gr->addCol("igk-col-3-2")->addDiv(), array(
"cladminDomain"=>array("require"=>1, "attribs"=>array("placeholder"=> "your site domain", "value"=>$app->Configs->website_domain)),
"cladminWebPageTitle"=>array("require"=>1, "attribs"=>array("placeholder"=> "main site title" ,"value"=>$app->Configs->website_title)),
"cladminPassword"=>array("type"=>"password"),
"cladminrePassword"=>array("type"=>"password"),
));


//mysql page
$d = $hpage->addDiv()->setId("mysqldbsetting");
$d->addDiv()->addSectionTitle(4)->setStyle("font-size:2.8em; font-family:'Roboto', sans-serif;")->Content = R::ngets("title.mysqldbsetting");

$g = $d->addDiv();
$gr = $g->addRow();
$gr->addCol("igk-col-3-1")->addDiv()->addSvgSymbol("mysql_logo");

igk_html_buildform($gr->addCol("igk-col-3-2")->addDiv(), 
array(
"clDbName"=>array("required"=>1, "attribs"=>array("value"=>"igkdev")),
"clDbServer"=>array("required"=>1, "attribs"=>array("value"=>"localhost")),
"clDbUserLogin"=>array("required"=>1, "attribs"=>array("value"=>"root")),
"clDbUserPassword"=>array("type"=>"password"),
"clDbUserRePassword"=>array("type"=>"password")
)
);




// $hpage->setCallback("install", <<<EOF
// // \$v = igk_post_uri("\$uri",array('action'=>'install'));
// igk_wln(\$_REQUEST);
// igk_wln(base64_decode(igk_getv(\$_REQUEST['q'])));
// igk_wln(\$_POST);

// igk_exit();
// //clear wize install
// IGKApp::getInstance()->Session->setParam("igk_wizeinstall", null);
// igk_navto("/Configs");
// igk_exit();
// EOF
// );

// $us ="";//igk_get_component_uri($hpage, "install");

$b = $dv->addActionBar();
$b->addButton("", R::ngets("btn.prev"))
->setAttribute("igk-hpageview-role", "prev")
->setAttribute('onclick',"javascript: \$igk('#pageview').first().moveback(); return false;");//ns_igk.ajx.post('$us', 'action=prev', ns_igk.ajx.fn.replace_body); return false;");
$b->addButton("", R::ngets("btn.next"))
->setAttribute("igk-hpageview-role", "next")
->setAttribute('onclick',"javascript: \$igk('#pageview').first().movenext(); return false;");// ns_igk.ajx.post('$us', 'action=next', ns_igk.ajx.fn.replace_body); return false;");


//because of form disabling on hit enter
// $b->addInput("","submit", R::ngets("btn.install"))
// ->setClass("igk-btn-default igk-pull-right")
// ->setAttribute("igk-hpageview-role", "submit");

$b->addInput("","submit", R::ngets("btn.install"))
->setClass("igk-btn-default igk-pull-right")
->setAttribute("igk-hpageview-role", "submit")
// ->setAttribute('onclick',"javascript:  this.form.submit(); return false;");
->setAttribute('onclick',"javascript:  this.form.submit(); return false;");
//ns_igk.winui.postform(ajx.post('$us', 'action=install', ns_igk.ajx.fn.replace_body); 


$c->addDiv()->setStyle("padding:1.0em 0px;")->addRow()->addDiv()->setClass("alignc")->addIGKCopyright();


$doc->RenderAJX();
igk_exit();

?>