<?php 


function igk_html_node_mediaImg($base){
	$n = igk_createNode("div");
	$n["class"] = "igk-winui-media-img";
	$n["igk:base"] = $base;
	return $n;
}
$t->ClearChilds();

// igk_css_bind_file($this, $this->getPrimaryCssFile());

$dv = $t->addDiv();
$s = $dv->addSpan()->setClass("floatr");
$s->addForm()->addAJXA($this->getUri("addNewTemplate_ajx"))->setClass("igk-btn")->Content = R::ngets("btn.create");

$dv->addSpan()->setClass("floatl")->addSectionTitle("5")->setFont("arial")->Content = R::ngets("title.mytemplates");

$dv->addClearFloatBox();

$r = $this->Db->getInstallTemplates();
if (!$r || $r->RowCount==0){
	$dv->addDiv()->Content = "/!\\ No Templates installed";
	// $dv->addObData($r);
}
else{
	//view template lists
	$dv = $t->addDiv();
	//$dv->addTemplate($this, "templateitem.template", $r->Rows);
	// igk_debug(1);
	igk_html_binddata($this, $dv, "templateitem.template", $r->Rows);
	// igk_debug(0);
	$dv->setClass("fitw igk-clear-cell") ;//addClear();
	$dv->addDiv()->setClass("igk-clear-cell");
}


// $dv->addForm()->addBtn("btn.uninstall","btn.uninstall");
$dv = $t->addDiv();
// $dv->setContent("search");



$dv = $t->addDiv();
$dv->addSectionTitle("5")->setFont("arial")->Content = R::ngets("title.onlinetemplates");
// $dv->addDiv()->addAJXUriLoader($this->getUri("avail_t_ajx"));
$dv->addA("http://balafon.igkdev.com/templates")->Content = "Visit balafon.igkdev.com/templates";


$dv = $t->addDiv();
$dv->addSectionTitle("5")->setFont("arial")->Content = R::ngets("title.loadTemplate");
$frm = $dv->addForm();
$frm->addNotifyHost("template://msg");
$frm->addajxPickFile($ctrl->getUri("loadtemplate_package_ajx"), "{complete:igk.ajx.fn.complete_ready('^form')}")->setClass("igk-btn igk-btn-default")->Content = R::ngets("btn.loadandinstall.templates");



// $t->addAJXA($this->getUri("demo_click_ajx"))->setContent("click me");
// $t->addAJXA($this->getUri("demo_configpage_ajx"))->setContent("click me");

// $dv->addA("http://balafon.igkdev.com/templates")->Content = "Visit balafon.igkdev.com/templates";
?>