<div id="description" class="description" >
Charger une resource image.
le site accepte les fichier .png , jpeg, et bmp . 
<ul>
	<li>le repertoire sert à charger l'image dans un repertoire spécifique du rértoire &lt;%System%&gt;/Img</li>
	<li><span class="clbolder">Nom :</span> spécifier la clef qui sera utilisé pour identifier l'image</li>
	<li><span class="clbolder" >fichier :</span> parcourez votre ordinateur à la rechercher </li>
</ul>
</div>
