<div>
Configurer le theme de votre site internet sur cette page. A travers la page 
Créer, éditer ou ajouter des classes qui seront utilisées pour configuer l'apparence de votre site.
<br />
<remark>
Une connaissance du css 3.0 est nécessaire pour obtenir de meilleur résultat. N'utiliser pas les " , séparer les attributs pas des ;
</remark>
<br />
[nom_de_la_propriété] : [valeur];
<br />
exemple<br />
<code>background-color: red; </code>
<table>

<tr>
	<th>Nom</th><th>Description</th><th>Exemple</th>
</tr>
<tr>
	<td>bgcl</td><td>couleur d'arrière pan</td><td>Exemple : [bgcl:background_cl]</td>
</tr>
<tr>
	<td>bgres</td><td>Image d'arrière plan. Sera remplacer par background-image:</td><td>Exemple : [bgres:background_cl]</td>
</tr>
<tr>
	<td>fcl</td><td>couleur du texte</td><td>Exemple : [fcl:police_cl]</td>	
</tr>
<tr>
	<td>fn</td><td>Nom de la police</td><td>[fn:police_cl]</td>	
</tr>
<tr>
	<td>ftn</td><td>Nom de la police remplacer par = font-family: =  </td><td>[ftn:police_cl]</td>	
</tr>
<tr>
	<td>pal</td><td>Nom de la couleur </td><td>[pal:police_cl]</td>	
</tr>
<tr>
	<td>palbgcl</td><td>Nom de la couleur de palette pour l'arrière plan</td><td>[palbgcl:palette_1]</td>	
</tr>
<tr>
	<td>palfcl</td><td>Nom de la couleur de la couleur de palette pour la couleur du texte </td><td>[palfcl:palette_1]</td>	
</tr>
<tr>
	<td colspan="3">&nbsp;</td>
</tr>
<tr>
	<td>{sys:}</td><td>permet utilisation des racourcis de style systeme</td><td>{sys:fitw fith posab}</td>	
</tr>
<tr>
	<td>{linkname}</td><td>lien vers un style déjà spécifier</td><td>pour une class nommé "hscroll" on aura {hscroll}</td>	
</tr>
<tr>
	<td>(:linkname)</td><td>lien vers la racine d'un style. note: celui-ci doit être unique</td><td>(:.horizontalmenu)</td>	
</tr>
</table>
<div>