<?php


$doc->setHeaderColor("#0064FF");//"#FFA500");
// $doc->Title = R::ngets("title.app_1", $this->ServiceName);
 
 $t->clearChilds();
 $t->Content = null;
 // $t->addHeaderBar($this->ServiceName);
 
$n = $t->addDiv();
 
$r = $n->addRow()->setStyle("padding-left:0px; padding-right:0px; margin-left:0px; margin-right:0px;overflow:hidden; background-color:#0064ff; color:#fefefe");
$h1 = $r->addDiv()
->setStyle("margin-left:-10px; margin-right:-10px; position:relative;")
->setClass(" igk-col-lg-12-2 fith presentation");

$dv = $h1->addDiv();
$dv["class"]="posab fith bdr-1";
$dv["style"]="z-index:1";
$dv->addA($this->getRootUri())->Content = "back";

$ct = $h1->addDiv()
->setClass("dispb no-decoration");
$ct->add("span")
->setClass("dispib posr")
->setStyle("left:10px; top:12px;")
->Content = igk_web_get_config("company_name");
$ct->addDiv()->setClass("igk-title-4")->Content = $this->ServiceName;
$r->addDiv()->setClass("igk-col-lg-12-10 .ibox");
	
// return;	
	
 
 // $r = $h->addRow()->setClass("no-margin");
	// $h1 = $r->addDiv()
	// ->setClass(" igk-col-lg-12-2 fith presentation");
	// $t = $h1->addDiv()
	// ->setClass("dispb no-decoration");
	
	// $r->add("span")
	// ->setClass("dispib posr")
	// ->setStyle("left:10px; top:12px;")
	// ->Content = igk_web_get_config("company_name");//igk_sys_domain_name();
	
	
	// $r->addDiv()->setClass("igk-title-4")->Content = $this->ServiceName;
// $r->addDiv()->setClass("igk-col-lg-12-10 .ibox");
	
	
	
 
 $t->addDiv()->setStyle("padding:0px 10px;")->addRow()->addCol()->Content = $this->getServiceDescription();//addSectionTitle(4)->addDiv()->Content = "Service used to list all world country";
 
$n = $t->addWebMasterNode()->addRow()->setClass("no-margin")->addCol()->addDiv();
$ul = $n->add("ul");
$ul->addLi()->Content = "Location : ".$this->getDeclaredFileName();
 
 $t->addDiv()->addContainer()->addRow()->addCol("igk-col-3-3")->addDiv()->addNotifyHost(); 

 $t->addDiv()->addContainer()->addRow()->addCol("igk-col-3-3")->addDiv()
 ->addBindArticle($this, 
 $this->getParentArticle("list.functions.template"), 
 $this->getExposedServiceFunction()
 );
 
 //start web master setting node
 $ctn = $t->addWebMasterNode()->addDiv()->addContainer();
 
 $ac = $ctn->addSingleRowCol()->addDiv();
 $ac->addABtn($this->getServiceUri()."/wsdl/1?r=1")->Content = R::ngets("btn.srv.genWSDL");
 
 if ($this->getUseDataSchema())
	$ac->addABtn(igk_getctrl("api")->getAppUri("datadb/ctrl_gen_schema/".$this->Name))->Content = R::ngets("btn.srv.genXmlDataSchema");
 $ac->addABtn(igk_getctrl("api")->getAppUri("ctrl/initDb/".$this->Name))->Content = R::ngets("btn.srv.InitDb");
 $ac->addABtn(igk_getctrl("api")->getAppUri("ctrl/resetDb/".$this->Name))->Content = R::ngets("btn.srv.resetDb");
 
 $row = $ctn->addRow();
 
 $frm = $row->addCol()->addDiv()->addForm();
 $frm["action"]  = $this->getUri("cachewsl");
 $frm["igk-form-ajx"] = 1;
 $i  = $frm->add("input")->setAttributes(array("id"=>"btnCache", "type"=>"submit", 
 "value"=>"Cache WSDL"
 ));
 $i["class"] =  "igk-btn"; 
 if ($this->Configs->clServiceDisableWSDLCache){
	  $i["class"] =  "+igk-active";
 }
 
 
 $row->addCol()->addDiv()->addABtn($this->getServiceUri()."/clearwsdl_cache")->Content = R::ngets("btn.clearWSDLCache");
 
 
 
 $t->addDiv()->addContainer()->addSingleRowCol()->addDiv()->addIGKCopyright();
?>